[package]
name = "lazycloud"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
dirs = "6.0.0"
nix = { version = "0.30.1", features = ["signal"] }
owo-colors = "4.2.2"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.2"
